version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      patch-and-minor-updates:
        update-types:
          - patch
          - minor
      major-updates:
        update-types:
          - major
    ignore:
      - dependency-name: '@types/*'
