import type { ArticleEntity, UserEntity } from '../../shared/types/entities';

/**
 * Legacy demo seed data for current user/article example modules.
 */
export const defaultUsers: UserEntity[] = [
  { id: 1, account: 'admin', name: 'Admin', role: 'admin' },
  { id: 2, account: 'editor', name: 'Editor', role: 'editor' },
  { id: 3, account: 'alice', name: 'Alice', role: 'editor' },
];

export const defaultArticles: ArticleEntity[] = [
  { id: 1, title: 'Elysia + Bun 快速启动', author: 'Admin' },
  { id: 2, title: 'Vue3 + Alova 请求实践', author: 'Editor' },
  { id: 3, title: '前后端类型共享方案', author: 'Admin' },
];

/**
 * P0/P1 base seed data for sys_* tables.
 * NOTE: passwordHash uses plain seed text for now, should be replaced by real hash in auth migration.
 */
export const defaultSysRoles = [
  {
    id: 1,
    code: 'admin',
    name: '超级管理员',
    description: '系统内置角色',
    status: 1,
  },
  {
    id: 2,
    code: 'editor',
    name: '运营编辑',
    description: '运营/编辑角色',
    status: 1,
  },
];

export const defaultSysPermissions = [
  {
    id: 1,
    code: 'system:user:view',
    name: '查看用户',
    type: 3,
    module: 'system-user',
    status: 1,
  },
  {
    id: 2,
    code: 'system:user:create',
    name: '新增用户',
    type: 2,
    module: 'system-user',
    status: 1,
  },
  {
    id: 3,
    code: 'system:user:update',
    name: '编辑用户',
    type: 2,
    module: 'system-user',
    status: 1,
  },
  {
    id: 4,
    code: 'system:user:delete',
    name: '删除用户',
    type: 2,
    module: 'system-user',
    status: 1,
  },
  {
    id: 5,
    code: 'system:role:view',
    name: '查看角色',
    type: 3,
    module: 'system-role',
    status: 1,
  },
  {
    id: 6,
    code: 'system:role:assign-permission',
    name: '分配角色权限',
    type: 2,
    module: 'system-role',
    status: 1,
  },
  {
    id: 7,
    code: 'system:menu:view',
    name: '查看菜单',
    type: 3,
    module: 'system-menu',
    status: 1,
  },
  {
    id: 8,
    code: 'system:menu:sort',
    name: '菜单排序',
    type: 2,
    module: 'system-menu',
    status: 1,
  },
  {
    id: 9,
    code: 'system:config:view',
    name: '查看系统配置',
    type: 3,
    module: 'system-config',
    status: 1,
  },
  {
    id: 10,
    code: 'system:config:update',
    name: '更新系统配置',
    type: 2,
    module: 'system-config',
    status: 1,
  },
  {
    id: 11,
    code: 'system:dict:view',
    name: '查看字典',
    type: 3,
    module: 'system-dict',
    status: 1,
  },
  {
    id: 12,
    code: 'audit:log:view',
    name: '查看操作日志',
    type: 3,
    module: 'audit-log',
    status: 1,
  },
  {
    id: 13,
    code: 'monitor:online:view',
    name: '查看在线用户',
    type: 3,
    module: 'monitor-online',
    status: 1,
  },
  {
    id: 14,
    code: 'monitor:cache:view',
    name: '查看缓存监控',
    type: 3,
    module: 'monitor-cache',
    status: 1,
  },
  {
    id: 16,
    code: 'system:dept:view',
    name: '查看部门',
    type: 3,
    module: 'system-dept',
    status: 1,
  },
  {
    id: 17,
    code: 'system:dept:create',
    name: '新增部门',
    type: 2,
    module: 'system-dept',
    status: 1,
  },
  {
    id: 18,
    code: 'system:dept:update',
    name: '编辑部门',
    type: 2,
    module: 'system-dept',
    status: 1,
  },
  {
    id: 19,
    code: 'system:dept:delete',
    name: '删除部门',
    type: 2,
    module: 'system-dept',
    status: 1,
  },
  {
    id: 20,
    code: 'system:dept:toggle',
    name: '切换部门状态',
    type: 2,
    module: 'system-dept',
    status: 1,
  },
  {
    id: 21,
    code: 'monitor:job:view',
    name: '查看任务中心',
    type: 3,
    module: 'monitor-job',
    status: 1,
  },
  {
    id: 22,
    code: 'monitor:job:create',
    name: '新增任务',
    type: 2,
    module: 'monitor-job',
    status: 1,
  },
  {
    id: 23,
    code: 'monitor:job:update',
    name: '编辑任务',
    type: 2,
    module: 'monitor-job',
    status: 1,
  },
  {
    id: 24,
    code: 'monitor:job:toggle',
    name: '启停任务',
    type: 2,
    module: 'monitor-job',
    status: 1,
  },
  {
    id: 25,
    code: 'monitor:job:run',
    name: '手动执行任务',
    type: 2,
    module: 'monitor-job',
    status: 1,
  },
  {
    id: 26,
    code: 'dict:type:list',
    name: '查看字典类型',
    type: 3,
    module: 'system-dict',
    status: 1,
  },
  {
    id: 27,
    code: 'dict:type:create',
    name: '新增字典类型',
    type: 2,
    module: 'system-dict',
    status: 1,
  },
  {
    id: 28,
    code: 'dict:type:update',
    name: '编辑字典类型',
    type: 2,
    module: 'system-dict',
    status: 1,
  },
  {
    id: 29,
    code: 'dict:type:delete',
    name: '删除字典类型',
    type: 2,
    module: 'system-dict',
    status: 1,
  },
  {
    id: 30,
    code: 'dict:type:toggle',
    name: '切换字典类型状态',
    type: 2,
    module: 'system-dict',
    status: 1,
  },
  {
    id: 31,
    code: 'dict:item:list',
    name: '查看字典项',
    type: 3,
    module: 'system-dict',
    status: 1,
  },
  {
    id: 32,
    code: 'dict:item:create',
    name: '新增字典项',
    type: 2,
    module: 'system-dict',
    status: 1,
  },
  {
    id: 33,
    code: 'dict:item:update',
    name: '编辑字典项',
    type: 2,
    module: 'system-dict',
    status: 1,
  },
  {
    id: 34,
    code: 'dict:item:delete',
    name: '删除字典项',
    type: 2,
    module: 'system-dict',
    status: 1,
  },
  {
    id: 35,
    code: 'dict:item:toggle',
    name: '切换字典项状态',
    type: 2,
    module: 'system-dict',
    status: 1,
  },
  {
    id: 15,
    code: 'security:ip-blacklist:view',
    name: '查看 IP 黑名单',
    type: 3,
    module: 'security-ip-blacklist',
    status: 1,
  },
];

export const defaultSysMenus = [
  {
    id: 1,
    parentId: 0,
    name: '系统管理',
    routeName: 'System',
    path: '/system',
    component: 'layout/router-view',
    icon: 'settings-outline',
    type: 1,
    sort: 10,
    visible: 1,
    status: 1,
    keepAlive: 0,
    permissionCode: null,
  },
  {
    id: 2,
    parentId: 1,
    name: '用户管理',
    routeName: 'SystemUser',
    path: '/system/user',
    component: 'system/user/index',
    icon: 'people-outline',
    type: 2,
    sort: 10,
    visible: 1,
    status: 1,
    keepAlive: 1,
    permissionCode: 'system:user:view',
  },
  {
    id: 3,
    parentId: 1,
    name: '角色管理',
    routeName: 'SystemRole',
    path: '/system/role',
    component: 'system/role/index',
    icon: 'shield-outline',
    type: 2,
    sort: 20,
    visible: 1,
    status: 1,
    keepAlive: 1,
    permissionCode: 'system:role:view',
  },
  {
    id: 4,
    parentId: 1,
    name: '菜单管理',
    routeName: 'SystemMenu',
    path: '/system/menu',
    component: 'system/menu/index',
    icon: 'list-outline',
    type: 2,
    sort: 30,
    visible: 1,
    status: 1,
    keepAlive: 1,
    permissionCode: 'system:menu:view',
  },
  {
    id: 5,
    parentId: 1,
    name: '字典配置',
    routeName: 'SystemDictConfig',
    path: '/system/dict-config',
    component: 'system/dict-config/index',
    icon: 'book-outline',
    type: 2,
    sort: 40,
    visible: 1,
    status: 1,
    keepAlive: 1,
    permissionCode: 'system:dict:view',
  },
  {
    id: 6,
    parentId: 1,
    name: '操作日志',
    routeName: 'AuditLog',
    path: '/system/audit-log',
    component: 'system/audit-log/index',
    icon: 'document-text-outline',
    type: 2,
    sort: 50,
    visible: 1,
    status: 1,
    keepAlive: 1,
    permissionCode: 'audit:log:view',
  },
  {
    id: 7,
    parentId: 1,
    name: '在线用户',
    routeName: 'MonitorOnline',
    path: '/monitor/online',
    component: 'monitor/online/index',
    icon: 'pulse-outline',
    type: 2,
    sort: 60,
    visible: 1,
    status: 1,
    keepAlive: 1,
    permissionCode: 'monitor:online:view',
  },
  {
    id: 8,
    parentId: 1,
    name: '缓存监控',
    routeName: 'MonitorCache',
    path: '/monitor/cache',
    component: 'monitor/cache/index',
    icon: 'server-outline',
    type: 2,
    sort: 70,
    visible: 1,
    status: 1,
    keepAlive: 1,
    permissionCode: 'monitor:cache:view',
  },
  {
    id: 10,
    parentId: 1,
    name: '部门管理',
    routeName: 'SystemDept',
    path: '/system/dept',
    component: 'system/dept/index',
    icon: 'git-network-outline',
    type: 2,
    sort: 35,
    visible: 1,
    status: 1,
    keepAlive: 1,
    permissionCode: 'system:dept:view',
  },
  {
    id: 11,
    parentId: 1,
    name: '任务中心',
    routeName: 'MonitorJob',
    path: '/monitor/job',
    component: 'monitor/job/index',
    icon: 'timer-outline',
    type: 2,
    sort: 75,
    visible: 1,
    status: 1,
    keepAlive: 1,
    permissionCode: 'monitor:job:view',
  },
  {
    id: 9,
    parentId: 1,
    name: 'IP 黑名单',
    routeName: 'SecurityIpBlacklist',
    path: '/security/ip-blacklist',
    component: 'security/ip-blacklist/index',
    icon: 'ban-outline',
    type: 2,
    sort: 80,
    visible: 1,
    status: 1,
    keepAlive: 1,
    permissionCode: 'security:ip-blacklist:view',
  },
];

export const defaultSysUsers = [
  {
    id: 1,
    account: 'admin',
    passwordHash: 'admin123',
    nickname: '管理员',
    email: null,
    mobile: null,
    avatarUrl: null,
    deptId: 1,
    status: 1,
  },
  {
    id: 2,
    account: 'editor',
    passwordHash: 'editor123',
    nickname: '编辑',
    email: null,
    mobile: null,
    avatarUrl: null,
    deptId: 2,
    status: 1,
  },
];

export const defaultSysUserRoles = [
  { userId: 1, roleId: 1 },
  { userId: 2, roleId: 2 },
];

export const defaultSysRolePermissions = [
  { roleId: 1, permissionId: 1 },
  { roleId: 1, permissionId: 2 },
  { roleId: 1, permissionId: 3 },
  { roleId: 1, permissionId: 4 },
  { roleId: 1, permissionId: 5 },
  { roleId: 1, permissionId: 6 },
  { roleId: 1, permissionId: 7 },
  { roleId: 1, permissionId: 8 },
  { roleId: 1, permissionId: 9 },
  { roleId: 1, permissionId: 10 },
  { roleId: 1, permissionId: 11 },
  { roleId: 1, permissionId: 12 },
  { roleId: 1, permissionId: 13 },
  { roleId: 1, permissionId: 14 },
  { roleId: 1, permissionId: 15 },
  { roleId: 1, permissionId: 16 },
  { roleId: 1, permissionId: 17 },
  { roleId: 1, permissionId: 18 },
  { roleId: 1, permissionId: 19 },
  { roleId: 1, permissionId: 20 },
  { roleId: 1, permissionId: 21 },
  { roleId: 1, permissionId: 22 },
  { roleId: 1, permissionId: 23 },
  { roleId: 1, permissionId: 24 },
  { roleId: 1, permissionId: 25 },
  { roleId: 1, permissionId: 26 },
  { roleId: 1, permissionId: 27 },
  { roleId: 1, permissionId: 28 },
  { roleId: 1, permissionId: 29 },
  { roleId: 1, permissionId: 30 },
  { roleId: 1, permissionId: 31 },
  { roleId: 1, permissionId: 32 },
  { roleId: 1, permissionId: 33 },
  { roleId: 1, permissionId: 34 },
  { roleId: 1, permissionId: 35 },
  { roleId: 2, permissionId: 1 },
  { roleId: 2, permissionId: 5 },
  { roleId: 2, permissionId: 7 },
  { roleId: 2, permissionId: 9 },
  { roleId: 2, permissionId: 16 },
  { roleId: 2, permissionId: 21 },
  { roleId: 2, permissionId: 26 },
  { roleId: 2, permissionId: 31 },
];

export const defaultSysRoleMenus = [
  { roleId: 1, menuId: 1 },
  { roleId: 1, menuId: 2 },
  { roleId: 1, menuId: 3 },
  { roleId: 1, menuId: 4 },
  { roleId: 1, menuId: 5 },
  { roleId: 1, menuId: 6 },
  { roleId: 1, menuId: 7 },
  { roleId: 1, menuId: 8 },
  { roleId: 1, menuId: 9 },
  { roleId: 1, menuId: 10 },
  { roleId: 1, menuId: 11 },
  { roleId: 2, menuId: 1 },
  { roleId: 2, menuId: 2 },
  { roleId: 2, menuId: 10 },
  { roleId: 2, menuId: 11 },
];

export const defaultSysDepts = [
  {
    id: 1,
    parentId: 0,
    name: '总部',
    code: 'HEADQUARTER',
    sort: 1,
    status: 1,
    leader: 'Admin',
    phone: null,
    email: null,
  },
  {
    id: 2,
    parentId: 1,
    name: '运营部',
    code: 'OPS',
    sort: 10,
    status: 1,
    leader: 'Editor',
    phone: null,
    email: null,
  },
];

export const defaultSysJobs = [
  {
    id: 1,
    name: 'demo-daily-report',
    cron: '0 8 * * *',
    status: 1,
    args: '{"type":"daily-report"}',
    runCount: 0,
    remark: '示例任务：每日 08:00 触发',
  },
];

export const defaultSysDictTypes = [
  {
    id: 1,
    code: 'sys_common_status',
    name: '通用状态',
    status: 1,
    remark: '0 禁用, 1 启用',
  },
];

export const defaultSysDictItems = [
  {
    id: 1,
    dictTypeId: 1,
    label: '禁用',
    value: '0',
    sort: 10,
    status: 1,
    isDefault: 0,
  },
  {
    id: 2,
    dictTypeId: 1,
    label: '启用',
    value: '1',
    sort: 20,
    status: 1,
    isDefault: 1,
  },
];

export const defaultSysConfigs = [
  {
    id: 1,
    key: 'system.upload.maxSizeMb',
    value: '5',
    valueType: 2,
    groupName: 'upload',
    isPublic: 1,
    remark: '上传大小限制（MB）',
  },
  {
    id: 2,
    key: 'system.theme.defaultMode',
    value: 'light',
    valueType: 1,
    groupName: 'theme',
    isPublic: 1,
    remark: '默认主题',
  },
];
